# Generated by Django 5.2.11 on 2026-02-05 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='story',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_stories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storycaption',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captions_story', to='stories.story'),
        ),
        migrations.AddField(
            model_name='storymention',
            name='mentioned_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_mentions_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storymention',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions_story', to='stories.story'),
        ),
        migrations.AddField(
            model_name='storyreaction',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions_story', to='stories.story'),
        ),
        migrations.AddField(
            model_name='storyreaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_reactions_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storystyle',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='styles_story', to='stories.story'),
        ),
        migrations.AddField(
            model_name='storyview',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views_story', to='stories.story'),
        ),
        migrations.AddField(
            model_name='storyview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_views_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='storymention',
            unique_together={('story', 'mentioned_user')},
        ),
        migrations.AlterUniqueTogether(
            name='storyreaction',
            unique_together={('story', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='storyview',
            unique_together={('story', 'user')},
        ),
    ]
