# Generated by Django 6.0.1 on 2026-02-06 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='background_color',
            field=models.CharField(default='#E85D1A', max_length=7),
        ),
        migrations.AddField(
            model_name='storystyle',
            name='background_color',
            field=models.CharField(default='#E85D1A', max_length=7),
        ),
        migrations.AlterField(
            model_name='story',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='stories/media/'),
        ),
        migrations.AlterField(
            model_name='story',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('text', 'Text')], default='image', max_length=10),
        ),
    ]
