# Generated by Django 6.0.1 on 2026-02-10 10:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_story_background_color_storystyle_background_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
