# Generated by Django 6.0.1 on 2026-02-10 10:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_story_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
